name: Mobile Mess
favicon: null
layout_spectrum: 0.7322573000565171
typography_spectrum: 0.6971144720446318
title: Mobile Mess Blog
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#1775bb'
    - '#8cc840'
    - '#25ace3'
    - '#bdd3ea'
  brandStrength: 0.6875
  lightness: 0.9472176521085203
  saturation: 0.375
  rhythmicContrast: 0.25
purpose: []
